models: 
  - name: dim_airbnb__listings
    description: Cleansed table which contains Airbnb listings.
    data_tests:
      - min_row_count:
          arguments:
            min_rows: 1000
          config:
            severity: 'warn'
    columns:
      - name: listing_id
        description: Primary key for the listings.
        data_tests: 
          - unique
          - not_null
    
      - name: host_id
        description: The host's id. References host table.
        data_tests:
          - not_null
          - relationships: 
              arguments:
                to: ref('dim_airbnb__hosts')
                field: host_id
    
      - name: room_type
        description: Type of the appartement / room.
        data_tests:
          - accepted_values:
              arguments:    
                values: ['Private room', 'Shared room', 'Hotel room', 'Entire home/apt']
      
      - name: minimum_nights
        description: '{{ doc("dim_airbnb__listings__minimum_nights")}}'
        data_tests:
          - positive_values

  - name: dim_airbnb__hosts
    description: '{{ doc("dim_airbnb__hosts") }}'
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: Primary key for the hosts table. Sourced from `raw_hosts.id`.
        data_type: integer
        data_tests:
          - unique
          - not_null
      - name: host_name
        description: '{{ doc("dim_airbnb__hosts__host_name") }}'
        data_type: string
      - name: is_superhost
        description: '{{ doc("dim_airbnb__hosts__is_superhost") }}'
        data_type: string
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']
      - name: created_at
        description: Timestamp when the host record was first created in the source system.
        data_type: timestamp
        data_tests:
          - not_null
      - name: updated_at
        description: Timestamp of the most recent update to the host record in the source system.
        data_type: timestamp
        data_tests:
          - not_null


        
